### ISSUE TITLE
Generate PDF

### ISSUE THREAD

**Issue by tbm** [beancount/docs#17]
It would be nice to generate a PDF.

It seems there are several options to generate PDFs, including:

https://github.com/zhaoterryy/mkdocs-pdf-export-plugin

https://github.com/comwes/mkpdfs-mkdocs-plugin

**Comment by xuhcc** [comment]
You can do that from the Google doc: File -> Download -> PDF Document.

**Comment by tbm** [comment]
Right, but that's per file and not for the whole documentation.

Although... I've looked at the mkdocs plugin in the meantime and I'm not so impressed.  So I guess you can close this if you want.
