### ISSUE TITLE
How to trigger documntation regeneration

### ISSUE THREAD

**Issue by dnicolodi** [beancount/docs#18]
Is there a way to trigger the regeneration of the documentation or is it a manual process?

**Comment by xuhcc** [comment]
Currently it's a manual process, I do that once a week (usually on tuesdays).

**Comment by xuhcc** [comment]
1f4fee96c291fe508ddf41f815e83c6a40c9d081

**Comment by chrishas35** [comment]
Thoughts on leveraging GitHub Actions to do this automatically? Can be scheduled and now triggered via the web (https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/).

**Comment by xuhcc** [comment]
I'm not sure that GitHub actions can do what we need. 
In any case, someone needs to review the changes before committing them, because the googledoc parser does not always work perfectly.
