### ISSUE TITLE
Paragraph gets pulled into code block

### ISSUE THREAD

**Issue by dnicolodi** [beancount/docs#20]
The first paragraph of text after the first code block in this section https://beancount.github.io/docs/getting_started_with_beancount.html#emacs get incorrectly included in the code block. I don't see anything obviusly wrong with the Google Docs document. How can I fix this?

**Comment by xuhcc** [comment]
It's because every paragraph that starts with a text in monospace font is considered a code block: https://github.com/beancount/docs/blob/master/export.py#L66-L71

The easiest way to fix this is to add some regular text before `beancount-mode`. We can also try to parser logic more sophisticated.

**Comment by dnicolodi** [comment]
I see. Thank you for the explanation. I don't have time to work on refining the heuristic now. I reworded the paragraph. Can you please regenerate the documentation?

**Comment by xuhcc** [comment]
I updated the docs, but it still parser incorrectly because the first letter in paragraph is in monospace font (Consolas). At least that's what I see when I export the Google doc as Microsoft Word document:

`M`ost facilities commonly...

**Comment by dnicolodi** [comment]
Ops. Fixed.

**Comment by xuhcc** [comment]
Done! 8774e0e
