### ISSUE TITLE
Thoughts on Modernizing the Docs Website

### ISSUE THREAD

**Issue by neelsudhakaran** [beancount/docs#43]
Hi! I'm a longtime Beancount user, and I'm super grateful to the hard work of all the maintainers. I've been reading about v3 for a few months now, and I heard that some changes are on their way in regards to the docs (e.g. moving away from Google docs and removing the dependency on [furius.ca](https://furius.ca).

Given this transition, I was wondering if there was also interest in transitioning away from MkDocs to a more custom solution with a custom theme instead of Read the Docs. I'm open to ideas—and I'm flexible in implementation details—but I was thinking something along the lines of [Astro](https://astro.build) with [Starlight](https://starlight.astro.build) or [Next.js](https://nextjs.org) with [Nextra](https://nextra.site). Both options would allow to reuse the existing markdown documentations, I also believe they both offer enough flexibility to accommodate any other requirements the team might have.

I realize that there's not an explicit need for this, so I totally understand if this is not something you're interested in pursuing. However, if it is, I'd be more than happy to take responsibility for doing this.

Please feel free to let me know your thoughts! Thank you for your time.

**Comment by xuhcc** [comment]
MkDocs is still actively developed ([1.6.0 was released on 2024-04-20](https://www.mkdocs.org/about/release-notes/)). The dependencies in requirements.txt can be updated, but I don't see any reason to use a different generator.

**Comment by neelsudhakaran** [comment]
Okay, no worries. Thank you for looking into it!
