### ISSUE TITLE
Some pages missing in conversion

### ISSUE THREAD

**Issue by tbm** [beancount/docs#9]
https://xuhcc.github.io/beancount-docs/06_beancount_language_syntax.html says

> For a deeper discussion of how and when to use payees or not, see Payees, Subaccounts, and Assets.

Also:

> Same for "There is a proposal pending to allowing"

Both are links to Same for furius.ca.  Any reason these aren't converted?

**Comment by xuhcc** [comment]
The parser only converts documentation pages mentioned in the index https://docs.google.com/document/d/1RaondTJCS_IUPBHFNdT8oqFKJjVJDsfsn6JEjBG04eA/edit

**Comment by xuhcc** [comment]
Second link leads to a todo, I don't think it belongs to documentation.
